Add guile link commands

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -10,7 +10,7 @@ dnl Created:          Mon Jun 30 15:10:13 1997
 dnl Last Modified:    Wed Aug  4 09:52:09 1999				      
 dnl            by:    Bruce Korb <autogen@linuxbox.com>			      
 dnl --------------------------------------------------------------------
-dnl Code: $Id: configure.in,v 2.29 1999/11/03 05:57:30 bruce Exp $
+dnl Code: $Id: configure.in,v 2.30 1999/11/11 04:06:15 bruce Exp $
 dnl --------------------------------------------------------------------
 
 AC_INIT(agen5/autogen.c)
@@ -22,7 +22,7 @@ AC_CONFIG_AUX_DIR(config)
 AC_CANONICAL_SYSTEM
 AM_INIT_AUTOMAKE($PACKAGE, $VERSION)
 
-ifdef([AC_REVISION],AC_REVISION($Revision: 2.29 $),)dnl
+ifdef([AC_REVISION],AC_REVISION($Revision: 2.30 $),)dnl
 
 # ----------------------------------------------------------------------
 # Substitute VERSION vars here, so that they can be used by the Makefile
@@ -158,6 +158,13 @@ AG_CHECK_SYS_SIGLIST
 test -f ./snprintfv/snprintfv/snprintfv.h \
   && rm -f ./snprintfv/snprintfv.h \
   && ln -s `pwd`/snprintfv/snprintfv/snprintfv.h ./snprintfv/
+GUILE_LINK=`guile-config link`
+if [ -z "$GUILE_LINK" ]
+then
+    echo 'Cannot find `guile-config'\' configurator >&2
+    exit 1
+fi
+AC_SUBST(GUILE_LINK)
 
 [M4_SRC=`cd $srcdir/config ; echo [a-z]*.m4`]
 AC_SUBST(M4_SRC)
