rework the names of executables used in bootstrapping et al.

diff --git a/compat/Makefile.am b/compat/Makefile.am
--- a/compat/Makefile.am
+++ b/compat/Makefile.am
@@ -2,14 +2,14 @@
 ## ---------------------------------------------------------------------
 ## Makefile.am -- process this file with automake to produce Makefile.in
 ##
-## Time-stamp:      "2004-02-01 13:24:27 bkorb"
+## Time-stamp:      "2004-10-27 19:50:36 bkorb"
 ## Copyright (c):   1997-2004 by Bruce Korb
 ## Author:          Bruce Korb <bkorb@gnu.org>
 ## Maintainer:      Bruce Korb <bkorb@gnu.org>
 ## Created:         Mon Jun 30 15:35:12 1997				      
 ##            by: bkorb
 ## ---------------------------------------------------------------------
-## $Id: Makefile.am,v 3.4 2004/02/01 21:26:46 bkorb Exp $
+## $Id: Makefile.am,v 3.5 2004/10/30 20:43:56 bkorb Exp $
 ## ---------------------------------------------------------------------
 ## Code:
 
@@ -24,15 +24,19 @@ all:
 	:
 
 strsignal.h : strsignal.def strsignal.tpl
-	@if $(AGEXE) --version >&- 2>&- ; then \
-	  echo $(AGEXE) -L $(srcdir) $(srcdir)/strsignal.def ; \
+	@if $(AGexe) --version >&- 2>&- ; then \
+	  echo $(AGexe) -L $(srcdir) $(srcdir)/strsignal.def ; \
 	  top_srcdir=$(top_srcdir) top_builddir=$(top_builddir) \
-	    $(AGEXE) -L $(srcdir) $(srcdir)/strsignal.def ; \
+	    $(AGexe) -L $(srcdir) $(srcdir)/strsignal.def ; \
+	elif $(AGnam) --version >&- 2>&- ; then \
+	  echo $(AGnam) -L $(srcdir) $(srcdir)/strsignal.def ; \
+	  top_srcdir=$(top_srcdir) top_builddir=$(top_builddir) \
+	    $(AGnam) -L $(srcdir) $(srcdir)/strsignal.def ; \
 	else \
 	  if test -s $(srcdir)/$@; then \
-	   echo "WARNING: $(AGEXE) not available, current $(srcdir)/$@ used"; \
+	   echo "WARNING: $(AGnam) not available, current $(srcdir)/$@ used"; \
 	  else \
-	   echo "ERROR: $(srcdir)/$@ has been corrupted"; \
+	   echo "ERROR: $(srcdir)/$@ has been corrupted"; exit 1;\
 	  fi; \
 	fi
 
