clean up the declarations of procedures

diff --git a/compat/Makefile.am b/compat/Makefile.am
--- a/compat/Makefile.am
+++ b/compat/Makefile.am
@@ -2,19 +2,19 @@
 ## ---------------------------------------------------------------------
 ## Makefile.am -- process this file with automake to produce Makefile.in
 ##
-## Time-stamp:      "2004-11-01 08:40:35 bkorb"
+## Time-stamp:      "2005-01-08 11:43:58 bkorb"
 ## Copyright (c):   1997-2004 by Bruce Korb
 ## Author:          Bruce Korb <bkorb@gnu.org>
 ## Maintainer:      Bruce Korb <bkorb@gnu.org>
 ## Created:         Mon Jun 30 15:35:12 1997				      
 ##            by: bkorb
 ## ---------------------------------------------------------------------
-## $Id: Makefile.am,v 4.1 2005/01/01 00:20:58 bkorb Exp $
+## $Id: Makefile.am,v 4.2 2005/01/09 03:20:27 bkorb Exp $
 ## ---------------------------------------------------------------------
 ## Code:
 
-EXTRA_DIST = bootstrap.dir compat.h libgen.h pathfind.c strftime.c \
-	strcspn.c strsignal.c strsignal.def strsignal.h strsignal.tpl
+EXTRA_DIST = bootstrap.dir compat.h pathfind.c strftime.c \
+	strsignal.c strsignal.def strsignal.h strsignal.tpl
 
 GEN_SRC    = strsignal.h
 MAINTAINERCLEANFILES = Makefile.in
@@ -31,12 +31,10 @@ strsignal.h : strsignal.def strsignal.tpl
 	  echo $(AGnam) -L $(srcdir) $(srcdir)/strsignal.def ; \
 	  top_srcdir=$(top_srcdir) top_builddir=$(top_builddir) \
 	    $(AGnam) -L $(srcdir) $(srcdir)/strsignal.def ; \
+	elif test -s $(srcdir)/$@; then \
+	  echo "WARNING: $(AGnam) not available, current $(srcdir)/$@ used"; \
 	else \
-	  if test -s $(srcdir)/$@; then \
-	   echo "WARNING: $(AGnam) not available, current $(srcdir)/$@ used"; \
-	  else \
-	   echo "ERROR: $(srcdir)/$@ has been corrupted"; exit 1;\
-	  fi; \
+	  echo "ERROR: $(srcdir)/$@ has been corrupted"; exit 1;\
 	fi
 
 # Makefile.am ends here
