many aesthetic cleanups.
* agen5/agDep.c (start_dep_file): handle temp suffix here so it can
  be done consistently.  Also, only list program name in comment once.
  (tidy_dep_file) check for target == dep file after moving dep file.
  (wrap_up_depends): emit cleanup rules on request
* agen5/ag-text.def (DEP_FILE_CLOBBER_FMT): cleanup format
* agen5/*: replace AG_BOOL with stdbool definitions
* autoopts/autogen.map (inversion): new char class
* autoopts/enum.c (find_name): use it.  Set error message format
  pointer when a too-large number is used for an enum.
* autoopts/usage-txt.def (TooLarge): new error message
* autoopts/test/keyword.test: test ~0/-1
* autoopts/test/vendor.test: adjust for stdbool
* autoopts/tpl/cmd-doc.tlib (get-cvt): function for converting
  texi-isms to man page/mdoc page isms for descrip and doc attributes
* autoopts/tpl/optlib.tlib (get-text): function for stripping
  texi-isms entirely for use in help text.
* compat/compat.h (stdbool.h): new accommodation
* config/bootstrap.shlib (run_ag): use -MP option
* config/misc.def: check stdbool.h header
* autoopts/tpl/aginfo.tpl: disable
* autoopts/tpl/agman1.tpl: disable
* agen5/defLex.c (build_here_str): stop stripping tabs with backslash
  tab, and skip the backslash, too.
* agen5/ag-text.def (DEP_FILE_WRAP_FMT): use it.
* everywhere: use global replacement tools to de-camelize many variables.

diff --git a/doc/mk-agen-texi-in b/doc/mk-agen-texi-in
--- a/doc/mk-agen-texi-in
+++ b/doc/mk-agen-texi-in
@@ -1,6 +1,6 @@
 #! @SHELL@
 
-# Time-stamp:        "2012-01-29 15:15:47 bkorb"
+# Time-stamp:        "2012-03-04 19:13:18 bkorb"
 #
 ##  This file is part of AutoGen.
 ##
@@ -31,26 +31,25 @@ die()
   echo
   cat ${LOG_FILE}
   trap : EXIT
-  echo leaving ${tmp_dir} in place
+  echo leaving ${TMPDIR} in place
   kill -TERM ${parent_pid}
   exit 1
 }
 
 set_config_values()
 {
-  tmp_dir=`pwd`/ag-texi-$$.d
+  TMPDIR=`pwd`/ag-texi-$$.d
   rm -rf ag-texi-*.d
-  mkdir ${tmp_dir} || die "cannot make ${tmp_dir} directory"
-  TMPDIR=${tmp_dir}
+  mkdir ${TMPDIR} || die "cannot make ${TMPDIR} directory"
   export TMPDIR
 
   case "$-" in
-  *x* ) trap "echo 'saved tmp dir:  ${tmp_dir}';chmod 777 ${tmp_dir}" EXIT
+  *x* ) trap "echo 'saved tmp dir:  ${TMPDIR}';chmod 777 ${TMPDIR}" EXIT
         VERBOSE=true ;;
-  *   ) trap "rm -rf ${tmp_dir}" EXIT
+  *   ) trap "rm -rf ${TMPDIR}" EXIT
         VERBOSE=false ;;
   esac
-  LOG_FILE=${tmp_dir}/texi.log
+  LOG_FILE=${TMPDIR}/texi.log
   exec 8>&2 2> ${LOG_FILE}
 
   test -z "${CC}"     && CC="@CC@"
@@ -84,7 +83,7 @@ set_config_values()
   for SHELL in @CONFIG_SHELL@ @SHELL@ `which bash` \
     /usr/xpg4/bin/sh `which sh` /bin/sh
   do test -x ${SHELL} && break ; done
-  export CC CFLAGS LIBS MAKE SHELL LOG_FILE tmp_dir
+  export CC CFLAGS LIBS MAKE SHELL LOG_FILE TMPDIR
 }
 
 setup_exports()
@@ -148,10 +147,10 @@ setup_exports()
 #
 run_getdefs()
 {
-  gd_cfg=${tmp_dir}/getdefs.cfg
+  gd_cfg=${TMPDIR}/getdefs.cfg
   exec 3> ${gd_cfg}
   cat >&3 <<-  EOCat
-	output      ${tmp_dir}/${GEN_BASE}.def
+	output      ${TMPDIR}/${GEN_BASE}.def
 	copy        ${OPTIONS_DEF}
 	srcfile
 	linenum
@@ -211,7 +210,7 @@ sanity_check()
   done
 
   cmd=${AGexe}
-  ${VERBOSE} && cmd=${cmd}" --trace=every --trace-out=>>${tmp_dir}/ag.log"
+  ${VERBOSE} && cmd=${cmd}" --trace=every --trace-out=>>${TMPDIR}/ag.log"
 }
 
 build_agdoc() {
@@ -231,21 +230,21 @@ build_agdoc() {
 	templ-dirs  ${srcdir}
 	templ-dirs  ${top_srcdir}/autoopts/tpl
 	base-name   ${GEN_BASE}
-	trace       every
-	trace-out   >>${tmp_dir}/ag.log
+	make-dep    F ${GEN_BASE}.dep
+	make-dep    P
 	_EOF_
     ${VERBOSE} && false && {
       echo 'trace       every'
-      echo "trace-out   >>${tmp_dir}/ag.log"
+      echo "trace-out   >>${TMPDIR}/ag.log"
     }
-  } > ${tmp_dir}/ag.ini
+  } > ${TMPDIR}/ag.ini
 
-  opts="--load-opts=${tmp_dir}/ag.ini -MF${GEN_BASE}.d"
-  cmd=`echo "${cmd}" ${opts} ${tmp_dir}/${GEN_BASE}.def`
+  opts="--load-opts=${TMPDIR}/ag.ini"
+  cmd=`echo "${cmd}" ${opts} ${TMPDIR}/${GEN_BASE}.def`
   echo "${PS4:-+} " ${cmd} >&8
 
   ${cmd} || {
-    cat ${tmp_dir}/ag.log
+    cat ${TMPDIR}/ag.ini ${TMPDIR}/ag.log
     die could not regenerate doc
   } >&2
 
