Correct shell.test use "--shell" option
SHELL environment is no longer used to specify the shell.
Respell runShell as shell_cmd.
Turn shell tracing off for doc build.

diff --git a/doc/mk-agen-texi-in b/doc/mk-agen-texi-in
--- a/doc/mk-agen-texi-in
+++ b/doc/mk-agen-texi-in
@@ -1,6 +1,6 @@
 #! @SHELL@
 
-# Time-stamp:        "2011-04-20 11:54:22 bkorb"
+# Time-stamp:        "2011-10-02 13:33:31 bkorb"
 #
 ##  This file is part of AutoGen.
 ##
@@ -34,6 +34,23 @@ die()
   echo leaving ${tmp_dir} in place
   kill -TERM ${parent_pid}
   exit 1
+}
+
+build_gnudocs()
+{
+  local sedcmd='/^@author @email/ {
+    s/.*{//
+    s/}.*//
+    s/@@*/@/g
+    p
+    q
+}'
+
+  title=`sed -n 's/^@title  *//p' agdoc.texi`
+  email=--email' '`sed -n "$sedcmd" agdoc.texi`
+  opts="--texi2html ${email}"
+  PS4='>${FUNCNAME:-gd}> ' ${SHELL} -x \
+    ${srcdir}/gendocs.sh $opts autogen "$title"
 }
 
 set_config_values()
@@ -215,35 +232,37 @@ sanity_check()
   ${VERBOSE} && cmd=${cmd}" --trace=every --trace-out=>>${tmp_dir}/ag.log"
 }
 
-#  Validate everything:
-#
-set_config_values
-setup_exports
-sanity_check
-run_getdefs
+build_agdoc() {
+  #  Validate everything:
+  #
+  set_config_values
+  setup_exports
+  sanity_check
+  run_getdefs
 
-env >&2
-exec 3> ${tmp_dir}/ag.ini
-cat >&3 <<- _EOF_
+  env >&2
+  exec 3> ${tmp_dir}/ag.ini
+  cat >&3 <<- _EOF_
 	timeout     ${timer}
 	templ-dirs  ${srcdir}
 	templ-dirs  ${top_srcdir}/autoopts/tpl
 	base-name   ${GEN_BASE}
 	_EOF_
-${VERBOSE} && {
-  echo 'trace       every'
-  echo "trace-out   >>${tmp_dir}/ag.log"
-} >&3
-exec 3>&-
+  ${VERBOSE} && {
+    echo 'trace       every'
+    echo "trace-out   >>${tmp_dir}/ag.log"
+  } >&3
+  exec 3>&-
 
-opts=--load-opts=${tmp_dir}/ag.ini
-cmd=`echo "${cmd}" ${opts} ${tmp_dir}/${GEN_BASE}.def`
-echo "${PS4:-+} " ${cmd} >&8
+  opts=--load-opts=${tmp_dir}/ag.ini
+  cmd=`echo "${cmd}" ${opts} ${tmp_dir}/${GEN_BASE}.def`
+  echo "${PS4:-+} " ${cmd} >&8
 
-${cmd} || die could not regenerate doc
-page_style=\
+  ${cmd} || die could not regenerate doc
+  page_style=\
 '\internalpagesizes{46\baselineskip}{6in}{-.25in}{-.25in}{\bindingoffset}{36pt}%'
-cat > autogen.texi <<- _EOF_
+
+  cat > autogen.texi <<- _EOF_
 	\input texinfo
 	@ignore
 	${page_style}
@@ -252,9 +271,16 @@ cat > autogen.texi <<- _EOF_
 	@setfilename autogen.info
 	@include ${GEN_BASE}.texi
 	_EOF_
-test -f ${GEN_BASE}.texi || die "MISSING: ${GEN_BASE}.texi"
+  test -f ${GEN_BASE}.texi || die "MISSING: ${GEN_BASE}.texi"
 
-exec 2>&8 8>&-
+  exec 2>&8 8>&-
+}
+
+case "$1" in
+agdoc.texi ) build_agdoc   ;;
+gnudocs    ) build_gnudocs ;;
+* )
+esac
 
 exit 0
 
