Factor out some common output file handling functionality, then augment it with better debug diagnostics.

diff --git a/doc/mk-agen-texi-in b/doc/mk-agen-texi-in
--- a/doc/mk-agen-texi-in
+++ b/doc/mk-agen-texi-in
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Time-stamp:        "2009-07-22 19:05:11 bkorb"
+# Time-stamp:        "2009-11-28 21:10:24 bkorb"
 #
 ##
 ##  This file is part of AutoGen.
@@ -20,154 +20,200 @@
 ##  You should have received a copy of the GNU General Public License along
 ##  with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-d=`dirname $0`
-d=`cd $d ; pwd`
-prog=${d}/`basename $0`
+d=$(dirname $0)
+d=$(cd $d ; pwd)
+prog=${d}/$(basename $0)
+parent_pid=$$
 
-test -z "${CC}"     && CC="@CC@"
-test -z "${CC}"     && `which cc`
-test -z "${CFLAGS}" && CFLAGS="@CFLAGS@"
-test -z "${LIBS}"   && LIBS="@LIBS@"
-test -z "${MAKE}"   && MAKE=`which make`
+die()
+{
+   exec 2>&8 1>&2 8>&-
+   echo "mk-agen-texi FAILED: $*"
+   echo
+   cat ${LOG_FILE}
+   trap : EXIT
+   kill -TERM ${parent_pid}
+   exit 1
+}
 
-INCLUDES="@DEFS@ "$(
+set_config_values()
+{
+  tmp_dir=ag-texi-$$.d
+  rm -rf ag-texi-*.d
+  mkdir ${tmp_dir} || die "cannot make ${tmp_dir} directory"
+  trap "rm -rf $(pwd)/${tmp_dir}" EXIT
+  LOG_FILE=${tmp_dir}/texi.log
+  exec 8>&2 2> ${LOG_FILE}
+
+  test -z "${CC}"     && CC="@CC@"
+  test -z "${CC}"     && $(which cc)
+  test -z "${CFLAGS}" && CFLAGS="@CFLAGS@"
+  test -z "${LIBS}"   && LIBS="@LIBS@"
+  test -z "${MAKE}"   && MAKE=$(which make)
+
+  INCLUDES="@DEFS@ "$(
 
     for d in . @srcdir@ @top_builddir@ @top_srcdir@ \
              @top_builddir@/autoopts @top_srcdir@/autoopts
     do
-        (\cd ${d} ; pwd)
+      (\cd ${d} ; pwd)
     done | \
-    sort -u | \
-    sed s/^/-I/ )
+      sort -u | \
+      sed s/^/-I/ )
 
-# Give preference to configured SHELL
-#
-d=${SHELL}
-SHELL=@SHELL@
-test -z "${SHELL}"  && SHELL=$d
-
-export CC CFLAGS LIBS MAKE SHELL INCLUDES
-
-# Now auto-export variables:
-#
-set -a
-
-top_builddir=`cd @top_builddir@ ; pwd`
-top_srcdir=`cd @top_srcdir@ ; pwd`
-srcdir=`cd @srcdir@ ; pwd`
-PATH=${top_builddir}/columns:${PATH}
-timer=`expr @AG_TIMEOUT@ '*' 5`
-
-eval `egrep '^AG_[A-Z_]*' ${top_srcdir}/VERSION`
-
-AGsrc=${top_srcdir}/agen5
-AGexe=@AGexe@
-GDexe=@GDexe@
-CLexe=@CLexe@
-
-LIBS=${LIBS}\ `find ${top_builddir}/autoopts -name libopts.a -print`
-OPTIONS_DEF=${AGsrc}/opts.def
-DIRECTIVESRC=${AGsrc}/defDirect.c
-GETDEF_SRC=$(
-  echo ${AGsrc}/func*.c ${AGsrc}/exp*.c ${AGsrc}/schemedef.scm ${DIRECTIVESRC} )
-
-ADDON_MENU=$(
-  for f in columns getdefs xml2ag
-  do
-    echo ${top_builddir}/${f}/${f}.menu
-  done)\ ${top_srcdir}/doc/snprintfv.menu
-
-ADDON_TEXI=$(
-  for f in columns getdefs xml2ag
-  do
-    echo ${top_builddir}/${f}/${f}.texi
-  done)\ ${top_srcdir}/doc/snprintfv.texi
-
-DOC_INCLUDES=$(
-  echo ${AGsrc}/defParse-fsm.c ${AGsrc}/opts.h
-  echo ${top_builddir}/agen5/autogen.menu ${top_builddir}/agen5/autogen.texi
-  echo ${top_builddir}/autoopts/libopts.texi )
-
-DOC_TEMPLATE=${srcdir}/auto_gen.tpl
-
-DOC_DEPENDS=$(
-  echo ${DOC_TEMPLATE} ${OPTIONS_DEF} ${ADDON_MENU} ${ADDON_TEXI}
-  echo ${DOC_INCLUDES} ${GETDEF_SRC} )
-
-set +a
-
-#  Validate everything:
-#
-bail_out() {
-   set -x
-
-   exec 2>&8
-   cat texi$$.log
-   echo >&2
-   echo "$*" >&2
-   exit 1
+  # Give preference to configured SHELL
+  #
+  d=@SHELL@
+  test -n "${d}" && SHELL=$d
+  test -z "${SHELL}" && {
+    SHELL=$(which bash)
+    test -z "${SHELL}" && SHELL=$(which sh)
+  }
+  export CC CFLAGS LIBS MAKE SHELL INCLUDES LOG_FILE tmp_dir
 }
 
-exec 8>&2 2> texi$$.log
-tmp_files=texi$$.log
-printf '\n\n\n\n' >&2
+setup_exports()
+{
+  # Now auto-export variables:
+  #
+  set -a
 
-set -x
+  top_builddir=$(cd @top_builddir@ ; pwd)
+  top_srcdir=$(cd @top_srcdir@ ; pwd)
+  srcdir=$(cd @srcdir@ ; pwd)
+  PATH=${top_builddir}/columns:${PATH}
+  timer=$(expr @AG_TIMEOUT@ '*' 5)
 
-# Make sure the executables are there
-#
-test -x ${AGexe} || (cd `dirname ${AGexe}` ; ${MAKE}) || exit 0
-test -x ${GDexe} || (cd `dirname ${GDexe}` ; ${MAKE}) || exit 0
-test -x ${CLexe} || (cd `dirname ${CLexe}` ; ${MAKE}) || exit 0
+  eval $(egrep '^AG_[A-Z_]*' ${top_srcdir}/VERSION)
 
-# See to it that the .texi files have been generated, too.
-#
-for f in ${ADDON_TEXI} ${top_builddir}/agen5/autogen.texi \
-         ${top_builddir}/autoopts/libopts.texi
-do
-  test -f ${f} || (
-    cd `dirname ${f}`
-    ${MAKE} `basename ${f}` >&2
-  ) || bail_out MAKE of ${f} failed.
-done
+  AGsrc=${top_srcdir}/agen5
+  AGexe=@AGexe@
+  GDexe=@GDexe@
+  CLexe=@CLexe@
+
+  LIBS=${LIBS}\ $(find ${top_builddir}/autoopts -name libopts.a -print)
+  OPTIONS_DEF=${AGsrc}/opts.def
+  DIRECTIVESRC=${AGsrc}/defDirect.c
+  GETDEF_SRC=$(
+    echo ${AGsrc}/func*.c \
+      ${AGsrc}/exp*.c \
+      ${AGsrc}/schemedef.scm \
+      ${DIRECTIVESRC} )
+
+  AGEN_TEXI=${top_builddir}/agen5/autogen.texi
+  DOC_TEXT=${top_srcdir}/doc/autogen-texi.txt
+
+  ADDON_MENU=$(
+    for f in columns getdefs xml2ag
+    do
+      echo ${top_builddir}/${f}/${f}.menu
+    done)\ ${top_srcdir}/doc/snprintfv.menu
+
+  ADDON_TEXI=$(
+    for f in columns getdefs xml2ag
+    do
+      echo ${top_builddir}/${f}/${f}.texi
+    done
+    echo ${top_srcdir}/doc/snprintfv.texi)
+
+  DOC_INCLUDES=$(
+    echo ${AGsrc}/defParse-fsm.c ${AGsrc}/opts.h
+    echo ${top_builddir}/agen5/autogen.menu ${top_builddir}/agen5/autogen.texi
+    echo ${top_builddir}/autoopts/libopts.texi )
+
+  DOC_TEMPLATE=${srcdir}/auto_gen.tpl
+
+  DOC_DEPENDS=$(
+    echo ${DOC_TEMPLATE} ${OPTIONS_DEF} ${ADDON_MENU} ${ADDON_TEXI} \
+         ${DOC_INCLUDES} ${GETDEF_SRC}  ${DOC_TEXT})
+
+  GEN_BASE=agdoc
+  set +a
+}
 
 # We have our executables and texi's.  Collect the definitions:
 #
-exec 3> getdefs$$.cfg
-tmp_files="${tmp_files} getdefs$$.cfg"
-cat >&3 <<-  EOCat
-	output      autogen.def
+run_getdefs()
+{
+  gd_cfg=${tmp_dir}/getdefs.cfg
+  exec 3> ${gd_cfg}
+  cat >&3 <<-  EOCat
+	output      ${tmp_dir}/${GEN_BASE}.def
 	copy        ${OPTIONS_DEF}
 	srcfile
 	linenum
 	template    auto_gen.tpl
+	assign      ag-texi = ${AGEN_TEXI}
 	EOCat
 
-tmp_files="${tmp_files} autogen.def"
-for f in ${GETDEF_SRC}
-do
-  echo "input      " ${f}
-done >&3
-exec 3>&-
-echo + ${GDexe} load-opt=getdefs$$.cfg >&8
-${GDexe} load-opt=getdefs$$.cfg || bail_out cannot run ${GDexe}
+  for f in ${ADDON_TEXI}
+  do
+    echo "assign      addon-texi = ${f}"
+  done >&3
 
-# Make sure we have all our sources and generate the doc
+  for f in ${GETDEF_SRC}
+  do
+    echo "input      " ${f}
+  done >&3
+  exec 3>&-
+  echo + ${GDexe} load-opt=${gd_cfg} >&8
+  ${GDexe} load-opt=${gd_cfg} || die cannot run ${GDexe}
+}
+
+sanity_check()
+{
+  # Make sure the executables are there
+  #
+  test -x ${AGexe} || (cd $(dirname ${AGexe}) ; ${MAKE}) || exit 0
+  test -x ${GDexe} || (cd $(dirname ${GDexe}) ; ${MAKE}) || exit 0
+  test -x ${CLexe} || (cd $(dirname ${CLexe}) ; ${MAKE}) || exit 0
+
+  # See to it that the .texi files have been generated, too.
+  #
+  for f in ${ADDON_TEXI} ${AGEN_TEXI} \
+           ${top_builddir}/autoopts/libopts.texi
+  do
+    test -f ${f} || (
+      cd $(dirname ${f})
+      ${MAKE} $(basename ${f}) >&2
+      test $? -ne 0 && die MAKE of ${f} failed.
+    )
+  done
+
+  # Make sure we have all our sources and generate the doc
+  #
+  for f in ${DOC_DEPENDS}
+  do test -f ${f} || die cannot find doc file: ${f}
+  done
+
+  cmd=${AGexe} # \ "--trace=every --trace-out=>>${tmp_dir}/ag.log"
+}
+
+#  Validate everything:
 #
-for f in ${DOC_DEPENDS}
-do test -f ${f} || bail_out cannot find doc file: ${f}
-done
-opts=`echo -t${timer} -L${srcdir} -L${top_srcdir} -L${top_srcdir}/autoopts`
-echo + ${AGexe} ${opts} autogen.def >&8
+set_config_values
+setup_exports
+printf '\n\n\n\n' >&2
 
-${AGexe} ${opts} autogen.def || bail_out could not regenerate doc
+set -x
 
+sanity_check
+run_getdefs
+
+env >&2
+opts="-t${timer} -L${srcdir} -L${top_srcdir} -L${top_srcdir}/autoopts"
+cmd=$(echo "${cmd}" --base=${GEN_BASE} ${opts} ${tmp_dir}/${GEN_BASE}.def)
+echo + ${cmd} >&8
+
+${cmd} || die could not regenerate doc
+
+cat > autogen.texi <<- _EOF_
+	\input texinfo
+	@include ${GEN_BASE}.texi
+	_EOF_
+test -f ${GEN_BASE}.texi || die "MISSING: ${GEN_BASE}.texi"
 set +x
-exec 2>&8
-
-# dump the temporary files
-#
-rm -f ${tmp_files}
+exec 2>&8 8>&-
 
 exit 0
 
