Make parseMacroArgs & optionPutShell much smaller (break 'em up).

diff --git a/config/bootstrap b/config/bootstrap
--- a/config/bootstrap
+++ b/config/bootstrap
@@ -3,7 +3,7 @@
 # ----------------------------------------------------------------------
 # bootstrap --- maintainer's bootstrap script
 #
-# Time-stamp:      "2010-02-24 15:14:28 bkorb"
+# Time-stamp:      "2010-02-24 17:37:41 bkorb"
 ##
 ##  This file is part of AutoGen.
 ##  AutoGen Copyright (c) 1992-2010 by Bruce Korb - all rights reserved
@@ -75,26 +75,25 @@ config_tools()
 
     #  Check for AutoGen version 5.
     #
-    AGexe=$(type autogen 2>/dev/null | \
-        sed 's@autogen is [^/]*/@/@')
+    AGexe=$(which autogen)
     case ${AGexe} in
     ( /* )
         v=$($AGexe --version)
         case "$v" in
         *"Ver. 5."* ) : ;;
-        * ) echo OUT OF DATE AutoGen: $v >&2
-            exit 1 ;;
+        * ) die "OUT OF DATE AutoGen: $v" ;;
         esac
         ;;
 
     ( * )
-        echo AutoGen requires autogen to bootstrap >&2
-        exit 1
+        die "AutoGen requires autogen to bootstrap"
         ;;
     esac
 
-    GDexe=$(type getdefs 2>/dev/null | sed 's@getdefs is [^/]*/@/@')
-    CLexe=$(type columns 2>/dev/null | sed 's@columns is [^/]*/@/@')
+    GDexe=$(which getdefs)
+    CLexe=$(which columns)
+    test -x "${GDexe}" -a -x "${CLexe}" || \
+        die "autogen support programs are missing"
     export AGexe GDexe CLexe
 
     # ------------------------------------------------------------------
@@ -105,11 +104,21 @@ config_tools()
     tools="autoconf autoheader aclocal automake libtoolize"
     for f in $tools
     do
+        tool=$(which ${f}) > /dev/null || die "No $f found"
         eval ${f}_reqver=$(
-            set -- $(${f} --version | sed 1q)
+            set -- $(${tool} --version | sed 1q)
             eval echo \${$#})
-        eval $(echo $f | tr a-z A-Z)=$(which ${f})
+        eval $(echo $f | tr a-z A-Z)=${tool}
     done
+
+    char_mapper=$(which char-mapper) 2>/dev/null
+    test -x "${char_mapper}" || {
+        char_mapper=$(
+            cd add-on/char-mapper >&2
+            make char-mapper >&2 || die "cannot make char-mapper"
+            echo ${PWD}/char-mapper)
+    }
+    export char_mapper
 
     echo bootstrapping in ${PWD}
 }
