test cleanup

diff --git a/autoopts/test/defs.in b/autoopts/test/defs.in
--- a/autoopts/test/defs.in
+++ b/autoopts/test/defs.in
@@ -3,7 +3,7 @@
 #
 # defs --- define the environment for autogen tests.
 #
-# Time-stamp:     "2010-12-09 18:24:09 bkorb"
+# Time-stamp:     "2010-12-10 12:37:43 bkorb"
 # Author:         Bruce Korb <bkorb@gnu.org>
 ##
 ##  This file is part of AutoOpts, a companion to AutoGen.
@@ -127,61 +127,62 @@ set_exe() {
   eval export ${1}=${d}/${f}
 }
 
-init_tests() {
-    logfile=`pwd`/testdir/${testname}.log
-    exec 8>&2 1>${logfile} 2>&1
-    set -x
+init_tests()
+{
+  logfile=`pwd`/testdir/${testname}.log
+  exec 8>&2 1>${logfile} 2>&1
 
-    TMPDIR=`pwd`/testdir/${testname}-tmpd
-    export TMPDIR
-    mkdir ${TMPDIR}
+  TMPDIR=`pwd`/testdir/${testname}-tmpd
+  export TMPDIR
+  mkdir ${TMPDIR}
 
-    f=`\cd ${LIBGUILE_PATH}/../bin && pwd`
-    PATH=${f}:${PATH}
+  f=`\cd ${LIBGUILE_PATH}/../bin && pwd`
+  PATH=${f}:${PATH}
 
-    set_exe AGexe
-    AGexe=${AGexe}
-    set_exe GDexe
-    set_exe CLexe
+  set_exe AGexe
+  AGexe=${AGexe}
+  set_exe GDexe
+  set_exe CLexe
 
-    builddir=`pwd`
-    testsubdir=testdir
-    INCS="-I${top_builddir} -I${top_builddir}/autoopts"
-    CFLAGS="${INCS} "`echo ${CFLAGS} | sed 's/-Werror//'`
+  set -x
+  builddir=`pwd`
+  testsubdir=testdir
+  INCS="-I${top_builddir} -I${top_builddir}/autoopts"
+  CFLAGS="${INCS} "`echo ${CFLAGS} | sed 's/-Werror//'`
 
-    export PATH
-    echo PATH is ${PATH} >&2
-    which columns >&2
-    which autogen >&2
+  export PATH
+  echo PATH is ${PATH} >&2
+  which columns >&2
+  which autogen >&2
 
-    lo_dir=${top_builddir}/autoopts
-    test -d ${lo_dir}/.libs && lo_dir=${lo_dir}/.libs
-    test "X${LD_LIBRARY_PATH}" = X || LD_LIBRARY_PATH=:${LD_LIBRARY_PATH}
-    LD_LIBRARY_PATH=${lo_dir}:${LIBGUILE_PATH}${LD_LIBRARY_PATH}
-    LIB=`echo ${lo_dir}/libopts.a`
-    export LD_LIBRARY_PATH
+  lo_dir=${top_builddir}/autoopts
+  test -d ${lo_dir}/.libs && lo_dir=${lo_dir}/.libs
+  test "X${LD_LIBRARY_PATH}" = X || LD_LIBRARY_PATH=:${LD_LIBRARY_PATH}
+  LD_LIBRARY_PATH=${lo_dir}:${LIBGUILE_PATH}${LD_LIBRARY_PATH}
+  LIB=`echo ${lo_dir}/libopts.a`
+  export LD_LIBRARY_PATH
 
-    if test ${GUILE_VERSION} -gt 107000
-    then
-      case ${AG_VERSION} in
-      *pre* ) GUILE_WARN_DEPRECATED=detailed ;;
-      *     ) GUILE_WARN_DEPRECATED=no ;;
-      esac
-      export GUILE_WARN_DEPRECATED
-    fi
+  if test ${GUILE_VERSION} -gt 107000
+  then
+    case ${AG_VERSION} in
+    *pre* ) GUILE_WARN_DEPRECATED=detailed ;;
+    *     ) GUILE_WARN_DEPRECATED=no ;;
+    esac
+    export GUILE_WARN_DEPRECATED
+  fi
 
-    test -f /usr/lib/libgen.so && {
-      case "${LIB}" in
-      *-lgen* ) : ;;
-      * ) LIB="${LIB} -lgen" ;;
-      esac
-    }
+  test -f /usr/lib/libgen.so && {
+    case "${LIB}" in
+    *-lgen* ) : ;;
+    * ) LIB="${LIB} -lgen" ;;
+    esac
+  }
 
-    AG_L=run_ag\ ao
-    agl_opts="-L${top_srcdir}/autoopts/tpl -L${top_builddir}/autoopts/tpl"
+  AG_L=run_ag\ ao
+  agl_opts="-L${top_srcdir}/autoopts/tpl -L${top_builddir}/autoopts/tpl"
 
-    export CC GUILE_VERSION LIBGUILE_PATH AG_VERSION AGexe AG_L GDexe CLexe \
-        agl_opts AG_L
+  export CC GUILE_VERSION LIBGUILE_PATH AG_VERSION AGexe AG_L GDexe CLexe \
+    agl_opts AG_L
 }
 
 be_silent()
@@ -200,10 +201,15 @@ be_silent()
 
   run_ag()
   {
-    local tfile=${testname}-aglog-${1}-$$.log
+    local opts=''
     shift
 
-    ${AGexe} ${agl_opts} -m "$@"
+    case " $* " in
+    ( *' -L'* ) : ;;
+    ( * ) opts="${agl_opts}" ;;
+    esac
+
+    ${AGexe} ${opts} "$@"
   }
 
   init_tests
@@ -221,10 +227,16 @@ be_verbose()
   {
     local tfile=${testname}-aglog-${1}-$$.log
     shift
+    local opts=''
     local tr="--trace=every --trace-out='>>${tfile}'"
 
+    case " $* " in
+    ( *' -L'* ) : ;;
+    ( * ) opts="${agl_opts}" ;;
+    esac
+
     MALLOC_CHECK_=2 \
-      ${AGexe} ${agl_opts} -m ${tr} "$@"
+      ${AGexe} ${opts} ${tr} "$@"
   }
 
   init_tests
@@ -342,6 +354,8 @@ trap "failure 'test ${testname} killed on timeout'" 15
 ## Local Variables:
 ## mode: shell-script
 ## indent-tabs-mode: nil
+## sh-indentation: 2
+## sh-basic-offset: 2
 ## End:
 
 # defs.in ends here
